@startuml
class AnimalShop {
    + price : int
    isPressed : bool
    Start() : void
    + SpawnObject() : void
}
MonoBehaviour <|-- AnimalShop
AnimalShop --> "button" GameObject
AnimalShop --> "boughtObject" GameObject
AnimalShop --> "pos" Transform
AnimalShop --> "onPress" UnityEvent
AnimalShop --> "onRelease" UnityEvent
@enduml
