@startuml
class DatabaseController {
    + Start() : void
    + sendData(t_cells:List<Vector3>) : void
    + postAfterGame() : void
    + PostMethod(jsonData:string) : IEnumerator
    GetIP() : string
}
class GameState {
    + ip : string
    + pathNr : int
    + cell1 : string
    + cell2 : string
    + cell3 : string
    + cell4 : string
    + cell5 : string
    + cell6 : string
    + cell7 : string
    + cell8 : string
    + cell9 : string
    + cell10 : string
}
MonoBehaviour <|-- DatabaseController
DatabaseController o-> "data" GameState
DatabaseController +-- GameState
@enduml
