@startuml
class FireBulletOnActivate {
    + fireSpeed : float = 20
    Start() : void
    Update() : void
    + FireBullet(arg:ActivateEventArgs) : void
}
MonoBehaviour <|-- FireBulletOnActivate
FireBulletOnActivate --> "bullet" GameObject
FireBulletOnActivate --> "spawnPoint" Transform
@enduml
