@startuml
class InventoryVR {
    UIActive : bool
}
MonoBehaviour <|-- InventoryVR
InventoryVR --> "leftActivate" InputActionProperty
InventoryVR --> "Inventory" GameObject
InventoryVR --> "Anchor" GameObject
@enduml
