@startuml
class MapEditor {
    resetColours() : void
    + Unlock(customID:int) : void
    + Lock(customID:int) : void
    + ChooseOption(res:RaycastHit, hitPoint:Vector3, pos:Vector3) : void
}
MonoBehaviour <|-- MapEditor
MapEditor --> "rayInteractor" XRRayInteractor
MapEditor --> "centre" Transform
MapEditor --> "left" Transform
MapEditor --> "camCentre" Transform
MapEditor --> "camLeft" Transform
MapEditor --> "rightSelect" InputActionProperty
MapEditor --> "rotate" InputActionProperty
MapEditor --> "CustomPath1" GameObject
MapEditor --> "BinPath1" GameObject
MapEditor --> "CustomPath2" GameObject
MapEditor --> "BinPath2" GameObject
MapEditor --> "loiterText" TextMeshPro
@enduml
