@startuml
class PathMover {
    + speed : float = 5.0f
    + mass : float = 5.0f
    + maxSteer : float = 15.0f
    + pathRadius : float = 1.0f
    + currentWaypointIndex : int = 0
    + id : int
    + hadLoiter : bool = false
    + canChangeY : bool = true
    + startWalkTime : int = 8
    + endWalkTime : int = 17
    + first : bool = false
    + late : bool = false
    + inside : bool = false
    Start() : void
    + SetDefaultPath(newId:int) : void
    Update() : void
    + GetStartTime() : int
    + Talk(time:int, pos:Vector3) : IEnumerator
}
class "List`1"<T> {
}
MonoBehaviour <|-- PathMover
PathMover --> "path<GameObject>" "List`1"
@enduml
