@startuml
class PlantController {
    + getPlant(name:string) : GameObject
    + getFruit(name:string) : GameObject
}
MonoBehaviour <|-- PlantController
PlantController --> "turnip" GameObject
PlantController --> "carrot" GameObject
PlantController --> "tomato" GameObject
PlantController --> "FruitTurnip" GameObject
PlantController --> "FruitCarrot" GameObject
PlantController --> "FruitTomato" GameObject
@enduml
