@startuml
class SeedBagController {
    + plantType : string
    + plotName : string
    timer : float = 0.5f
}
MonoBehaviour <|-- SeedBagController
SeedBagController --> "seed" GameObject
SeedBagController --> "rightSelect" InputActionProperty
SeedBagController --> "SpawnPoint" Transform
@enduml
