@startuml
class ShopKeeperMover {
    + speed : float = 5.0f
    + mass : float = 5.0f
    + maxSteer : float = 15.0f
    + pathRadius : float = 0.001f
    + currentWaypointIndex : int = 0
    + id : int
    + canChangeY : bool = true
    + StartWalkTime : int = 4
    + ShopRotation : int = 0
    + dayOff : int = 0
    Start() : void
    Update() : void
    + GetStartTime() : int
    + WorkToday() : bool
}
class "List`1"<T> {
}
MonoBehaviour <|-- ShopKeeperMover
ShopKeeperMover --> "path<GameObject>" "List`1"
@enduml
