@startuml
class Slot {
    _canPutIn : bool = true
    IsItem(obj:GameObject) : bool
    InsertItem(obj:GameObject) : void
    + RemoveItem() : void
    + SetPutIn(put:bool) : void
}
MonoBehaviour <|-- Slot
Slot --> "itemInSlot" GameObject
Slot --> "slotImage" Image
Slot --> "attachPoint" Transform
Slot --> "originalColour" Color
Slot --> "rightSelect" InputActionProperty
@enduml
